# Generated by Django 4.0.4 on 2023-12-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('is_new', models.BooleanField(default=False)),
                ('item_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('color_name', models.CharField(max_length=255)),
                ('color_group_code', models.CharField(max_length=255)),
                ('color_code', models.CharField(max_length=255)),
                ('hex_code', models.CharField(max_length=255)),
                ('size_group', models.CharField(max_length=255)),
                ('size_code', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('case_qty', models.IntegerField()),
                ('weight', models.CharField(max_length=255)),
                ('front_image', models.CharField(max_length=255)),
                ('back_image', models.CharField(max_length=255)),
                ('side_image', models.CharField(max_length=255)),
                ('gtin', models.CharField(max_length=255)),
                ('launch_date', models.IntegerField()),
                ('pms_color', models.CharField(max_length=255)),
                ('size_sort_order', models.IntegerField()),
                ('mktg_color_number', models.IntegerField()),
                ('mktg_color_name', models.CharField(max_length=255)),
                ('mktg_color_hex_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='alphabroder_integration.products')),
                ('gtin_number', models.CharField(max_length=255, unique=True)),
                ('mill_style_number', models.CharField(max_length=255)),
                ('cc', models.IntegerField(default=0)),
                ('cn', models.IntegerField(default=0)),
                ('fo', models.IntegerField(default=0)),
                ('gd', models.IntegerField(default=0)),
                ('kc', models.IntegerField(default=0)),
                ('ma', models.IntegerField(default=0)),
                ('ph', models.IntegerField(default=0)),
                ('td', models.IntegerField(default=0)),
                ('pz', models.IntegerField(default=0)),
                ('bz', models.IntegerField(default=0)),
                ('fz', models.IntegerField(default=0)),
                ('px', models.IntegerField(default=0)),
                ('fx', models.IntegerField(default=0)),
                ('bx', models.IntegerField(default=0)),
                ('gx', models.IntegerField(default=0)),
                ('drop_ship', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('item_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='price', serialize=False, to='alphabroder_integration.products')),
                ('gtin_number', models.CharField(max_length=255, unique=True)),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_per_dozen', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_per_case', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('mill_number', models.CharField(max_length=255)),
                ('mill_name', models.CharField(max_length=255)),
                ('markup_code', models.CharField(max_length=255)),
                ('full_feature_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='alphabroder_integration.category')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='products',
            name='style_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alphabroder_integration.style'),
        ),
    ]
