# Generated by Django 4.0.4 on 2024-01-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='variation_id',
        ),
        migrations.AlterField(
            model_name='variations',
            name='item_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
